In [1]:
import numpy as np

In [3]:
a = np.array([2, 4, 6])

In [4]:
a

array([2, 4, 6])

In [5]:
np.ones((2, 3), dtype=np.int)

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
np.zeros((15, 15))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [10]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.tile(np.arange(5), (5, 3))

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])

In [12]:
np.repeat([1, 2], 5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [13]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [14]:
np.matrix('1, 2; 3, 4')

matrix([[1, 2],
        [3, 4]])

You can create a structured array as well

In [16]:
x = np.array([('a', 0.8), ('b', 0.2)], dtype=[('label', 'a8'), ('prob', 'f8')])

In [17]:
x['label']

array([b'a', b'b'], dtype='|S8')

In [18]:
x['prob']

array([0.8, 0.2])

Numpy's broadcasting allows us to vectorize operations like addition, subtraction etc.

In [19]:
a = np.array([2, 4, 6])
b = np.array([8, 10, 12])

In [20]:
a + b

array([10, 14, 18])

In [22]:
a + 3

array([5, 7, 9])

In [19]:
a - 9

array([-7, -5, -3])

In [20]:
a * 10

array([20, 40, 60])

Broadcasting vectorizes the operation so that it's as if the scalars 1, 9 and 10 we're repeated to form an array with the same dimensions as a to allow the operation.

Some rules for Numpy broadcasting

Taken from the Numpy documentation - <br>
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

* they are equal, or
* one of them is 1

In [24]:
a = np.arange(100).reshape(20, 5)
b = np.arange(20).reshape(20, 1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [22]:
a + b

array([[  0,   1,   2,   3,   4],
       [  6,   7,   8,   9,  10],
       [ 12,  13,  14,  15,  16],
       [ 18,  19,  20,  21,  22],
       [ 24,  25,  26,  27,  28],
       [ 30,  31,  32,  33,  34],
       [ 36,  37,  38,  39,  40],
       [ 42,  43,  44,  45,  46],
       [ 48,  49,  50,  51,  52],
       [ 54,  55,  56,  57,  58],
       [ 60,  61,  62,  63,  64],
       [ 66,  67,  68,  69,  70],
       [ 72,  73,  74,  75,  76],
       [ 78,  79,  80,  81,  82],
       [ 84,  85,  86,  87,  88],
       [ 90,  91,  92,  93,  94],
       [ 96,  97,  98,  99, 100],
       [102, 103, 104, 105, 106],
       [108, 109, 110, 111, 112],
       [114, 115, 116, 117, 118]])

Some broadcasting exercises

In [25]:
a = np.ones((9, 8, 1, 3, 3))
b = np.ones((1, 8, 9, 1, 3))

Can they be broadcasted?

In [24]:
a + b

array([[[[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         ...,

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]],


        [[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         ...,

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]],


        [[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

    

In [26]:
a = np.ones((9, 1, 1))
b = np.ones((1, 9, 8))

Can they be broadcasted?

In [27]:
a + b

array([[[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2

In [39]:
# Added a new example
a = np.ones((1, 1, 1))
b = np.ones((8, 8, 8))
a + b

array([[[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2

<br>Indexing

In [40]:
a = np.arange(25)
print(a.shape)

(25,)


In [46]:
a[:, np.newaxis, np.newaxis]
a[:, np.newaxis, np.newaxis].shape

(25, 1, 1)

In [62]:
a = np.arange(25).reshape(5, 5, 1)

In [63]:
a.shape

(5, 5, 1)

In [64]:
print(a[0, ...])


[[0]
 [1]
 [2]
 [3]
 [4]]


In [65]:
a[1, :, :]
a

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23],
        [24]]])

In [66]:
a = a.squeeze()
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
a.shape

(5, 5)

In [68]:
a[:,:,np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23],
        [24]]])

In [41]:
a[:, :, np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23],
        [24]]])

In [73]:
a[1][1]

6

In [43]:
a[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

array([ 0,  6, 12, 18, 24])

In [86]:
b = np.arange(60).reshape(4,60//4)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [78]:
x = a[0:2].copy()
print(x)

[[100   1   2   3   4]
 [  5   6   7   8   9]]


In [79]:
x[0, 0] = 100
a[0, 0] = 0
print(x)

[[100   1   2   3   4]
 [  5   6   7   8   9]]


In [49]:
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

What will the output of this be?

In [51]:
a[::2, [1, 3, 4]]

array([[ 1,  3,  4],
       [11, 13, 14],
       [21, 23, 24]])

What if you wanted to access elements in a cross product manner? <br>
eg. (0, 0), (0, 2), (0, 3), (2, 0), (2, 2), (2, 3)

In [52]:
np.ix_([0, 2], [0, 2, 3])

(array([[0],
        [2]]), array([[0, 2, 3]]))

In [53]:
a[np.ix_([0, 2], [0, 2, 3])]

array([[100,   2,   3],
       [ 10,  12,  13]])

Exercise time!

In [88]:
a = np.arange(25).reshape((5, 5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [89]:
b = np.arange(75).reshape((5, 5, 3))
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]],

       [[60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71],
        [72, 73, 74]]])

In [104]:
print(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]

 [[60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]
  [72 73 74]]]


In [111]:
print(a.shape)
print(b.shape)
print(a[:, :, np.newaxis].shape)
c = (a[:, :, np.newaxis] + b)
print(c.shape)
d = c[::, ::2, [0, -1]]
print(d.shape)
print(d)

(5, 5)
(5, 5, 3)
(5, 5, 1)
(5, 5, 3)
(5, 3, 2)
[[[ 0  2]
  [ 8 10]
  [16 18]]

 [[20 22]
  [28 30]
  [36 38]]

 [[40 42]
  [48 50]
  [56 58]]

 [[60 62]
  [68 70]
  [76 78]]

 [[80 82]
  [88 90]
  [96 98]]]


* Add the two arrays together (remember the rules for broadcasting)
* Acess the first and last element of every alternate row

NumPy arrays are passed by reference

In [90]:
a = np.array([1, 2, 3, 4, 5])

In [91]:
b = a

In [92]:
b is a

True

In [93]:
np.may_share_memory(a, b)

True

In [94]:
a[1] = 100

In [95]:
print(a)

[  1 100   3   4   5]


In [96]:
print(b)

[  1 100   3   4   5]


In [97]:
b = np.array([1, 2, 3, 4, 5])

In [98]:
a = b.copy() # b[:]

In [99]:
a[1] = 9999

In [100]:
a

array([   1, 9999,    3,    4,    5])

In [101]:
b

array([1, 2, 3, 4, 5])

In [102]:
a = b[:]
print(b)

[1 2 3 4 5]


In [103]:
a

array([1, 2, 3, 4, 5])

In [104]:
a[1] = 99999

In [105]:
a

array([    1, 99999,     3,     4,     5])

In [106]:
b

array([    1, 99999,     3,     4,     5])

In [107]:
def func1(array):
    array *= 2
    return array

In [108]:
x = np.array([10])

In [109]:
y = func1(x)

In [110]:
y

array([20])

In [111]:
x

array([20])

In [112]:
def func2(array):
    array = array * 2
    return array

In [113]:
y = func2(x)

In [114]:
print(y)

[40]


In [115]:
x

array([20])

Behaviour is different for integers, floats etc.

In [89]:
x = 20

In [93]:
y = func1(x)

In [94]:
y

40

In [95]:
x

20

In [96]:
a = np.array([1, 2, 3])

In [97]:
b = a

In [98]:
c = [a, b]

In [99]:
c

[array([1, 2, 3]), array([1, 2, 3])]